USE SIP_USUARIO
GO

IF OBJECT_ID('tempdb.dbo.#ColunasDB1') IS NOT NULL DROP TABLE #ColunasDB1
GO

SELECT ID, OBJECT_NAME(ID) AS TABELA, SC.NAME AS COLUNA, SC.COLID
INTO #ColunasDB1
FROM SYSCOLUMNS SC
WHERE 0 = 0

--AND ID = OBJECT_ID('DiferencaATM') 
--AND NAME = 'ValorEntTes'

IF OBJECT_ID('tempdb.dbo.#ColunasDB2') IS NOT NULL DROP TABLE #ColunasDB2
GO

USE SIP_DESENV2
GO

SELECT ID, OBJECT_NAME(ID) AS TABELA, SC.NAME AS COLUNA, SC.COLID
INTO #ColunasDB2
FROM SYSCOLUMNS SC
WHERE 0 = 0


SELECT DB1.ID, DB1.COLID, DB1.TABELA, DB1.COLUNA
FROM #ColunasDB1 DB1
LEFT JOIN #ColunasDB2 DB2 
	ON DB2.TABELA = DB1.TABELA
	AND DB2.COLUNA = DB1.COLUNA
WHERE 0 = 0
AND DB2.COLUNA IS NULL
ORDER BY DB1.TABELA, DB1.COLID
