use msdb;

WITH CTE_RESTORE AS(

SELECT R.RESTORE_HISTORY_ID, R.RESTORE_DATE AS DATA_RESTAURACAO,B.BACKUP_START_DATE DATA_BACKUP,R.DESTINATION_DATABASE_NAME,R.USER_NAME FROM

RESTOREHISTORY R WITH(NOLOCK)

INNER JOIN BACKUPSET B WITH(NOLOCk)

       ON R.BACKUP_SET_ID = B.BACKUP_SET_ID


 

)

,CTE_REST1 AS (

SELECT MAX(DATA_RESTAURACAO) AS DT_LOAD,DESTINATION_DATABASE_NAME

FROM CTE_RESTORE

WHERE DATA_RESTAURACAO > '2017-01-01'

GROUP BY DESTINATION_DATABASE_NAME

--ORDER BY DESTINATION_DATABASE_NAME

)

SELECT *

FROM CTE_REST1

ORDER BY DT_LOAD