USE [SIPVIG_DSV]
GO

DECLARE @FUNCIONARIO INT;
DECLARE @EMPRESA INT;
DECLARE @DTPROMOCAO DATETIME;
DECLARE @MATRICULA INT;
DECLARE @EMPRESANOME VARCHAR(100);

DECLARE CSR_FUNCIONARIOS CURSOR FOR  
	SELECT A.FUNCIONARIO, A.EMPRESA, A.DTPROMOCAO, A.MATRICULA, C.NOMERESUMIDO AS EMPRESANOME
	FROM   FUNCIONARIO A WITH(NOLOCK)
	INNER JOIN RELACAOENTIDADE B ON B.RELACAOENTIDADE = A.EMPRESA 
	INNER JOIN ENTIDADE C ON C.ENTIDADE = B.PAPEL1
	WHERE  1 = 1 -- Selecionar os funcionários do chamado
	AND    A.FUNCIONARIO IN (220461, 165063, 247829, 194735, 127452);


OPEN CSR_FUNCIONARIOS;
FETCH NEXT FROM CSR_FUNCIONARIOS 
INTO @FUNCIONARIO, @EMPRESA, @DTPROMOCAO, @MATRICULA, @EMPRESANOME;

WHILE @@FETCH_STATUS = 0  
BEGIN  

	PRINT CONCAT('FUNCIONÁRIO: ', @FUNCIONARIO);

	--PRINT 'ATUALIZA DATA DE CORTE PARA ALOCACAOMO BASEADO NA DATA DE DEMISSAO';

	FETCH NEXT FROM CSR_FUNCIONARIOS 
	INTO @FUNCIONARIO, @EMPRESA, @DTPROMOCAO, @MATRICULA, @EMPRESANOME;
END;
CLOSE CSR_FUNCIONARIOS;
DEALLOCATE CSR_FUNCIONARIOS; 
