DECLARE @PERIODOINI DATETIME = CONVERT(DATETIME,  '16/06/2018'   ,103)
DECLARE @PERIODOFIM DATETIME = CONVERT(DATETIME,  '15/07/2018'   ,103)

;WITH REGISTROPONTO(DTINICIOPLANEJADO)
AS
(
        SELECT  DATEADD(DAY, 0, DATEDIFF(DAY, 0, @PERIODOINI)) AS DTINICIOPLANEJADO
        UNION ALL
        SELECT  DATEADD(DAY, 1, REGISTROPONTO.DTINICIOPLANEJADO) AS DTINICIOPLANEJADO
        FROM
                REGISTROPONTO
        WHERE
                REGISTROPONTO.DTINICIOPLANEJADO < @PERIODOFIM
)

SELECT  DTINICIOPLANEJADO
FROM
        REGISTROPONTO WITH (NOLOCK)
OPTION
        (MAXRECURSION 32767)