declare @retorno int


INSERT ATESTE(DATA_REF)

VALUES (GETDATE())

SELECT @retorno =@@Identity FROM ATESTE;

PRINT @retorno


/*
USE [SIPVIG_DSV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ATESTE](
	[ATESTE] [int] IDENTITY(1,1) NOT NULL,
	[DATA_REF] [datetime] NOT NULL DEFAULT GETDATE()
 CONSTRAINT [PK_ATESTE] PRIMARY KEY CLUSTERED 
(
	[ATESTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
*/
