SELECT EN.ENTIDADE,
       EN.TIPOENTIDADE,
       TE.DESCRICAO AS TIPOENTIDADE_DESCRICAO,
	   EN.NOMECOMPLETO,
	   EN.NOMERESUMIDO
FROM   ENTIDADE EN
INNER JOIN TIPOENTIDADE TE ON EN.TIPOENTIDADE = TE.TIPOENTIDADE;

SELECT RL.*
FROM   RELACAO RL;



SELECT EP2.NOMECOMPLETO AS  NOMECOMPLETOEMPRESA, EP2.NOMERESUMIDO AS NOMERESUMIDOEMPRESA,
	   EP1.NOMECOMPLETO AS NOMECOMPLETOCLIENTE, EP1.NOMERESUMIDO AS NOMERESUMIDOCLIENTE,
	   RE.*
FROM   RELACAOENTIDADE RE
INNER JOIN ENTIDADE EP1 ON EP1.ENTIDADE = RE.PAPEL1 --CLIENTE
INNER JOIN ENTIDADE EP2 ON EP2.ENTIDADE = RE.PAPEL2 --EMPRESA
WHERE  RE.RELACAO = 300 -- P1 É CLIENTE DO GRUPO EMPRESA P2
ORDER BY EP2.NOMECOMPLETO, EP2.NOMERESUMIDO,
	   EP1.NOMECOMPLETO, EP1.NOMERESUMIDO;



SELECT EA.*
FROM   ENTIDADEAUX EA
