DECLARE @CARGO INT = 10019--:CARGO
DECLARE @MATRIZ INT = 10001--:MATRIZ
DECLARE @FILIAL INT = 10003--:FILIAL
DECLARE @CARGOEMPRESAMAT INT = 10281--:CARGOEMPRESAMAT
DECLARE @CARGOEMPRESAFIL INT;

SELECT @CARGOEMPRESAFIL = CARGOEMPRESA
  FROM CARGOEMPRESA (NOLOCK)
 WHERE SITUACAO = 1
   AND CARGO = @CARGO
   AND EMPRESA = @MATRIZ;

SELECT @CARGOEMPRESAFIL;