DECLARE @SQLCOMMAND VARCHAR(MAX) =  NULL

SET @SQLCOMMAND = CONCAT(@SQLCOMMAND, 'DECLARE @TABELA TABLE (CODIGO INT, DESCRICAO VARCHAR(50));');

SET @SQLCOMMAND = CONCAT(@SQLCOMMAND, 'INSERT INTO @TABELA (CODIGO, DESCRICAO) VALUES (1, ''PRIMEIRO REGISTRO'');');
SET @SQLCOMMAND = CONCAT(@SQLCOMMAND, 'INSERT INTO @TABELA (CODIGO, DESCRICAO) VALUES (2, ''SEGUNDO REGISTRO'');');
SET @SQLCOMMAND = CONCAT(@SQLCOMMAND, 'INSERT INTO @TABELA (CODIGO, DESCRICAO) VALUES (3, ''TERCEIRO REGISTRO'');');

SET @SQLCOMMAND = CONCAT(@SQLCOMMAND, 'SELECT T.* FROM @TABELA T ORDER BY T.CODIGO;');

EXEC (@SQLCOMMAND)