BEGIN TRANSACTION C1;

UPDATE VERSAOCONTRATO SET SITUACAOCONTR = 4
FROM CONTRATO WITH (NOLOCK)
	INNER JOIN VERSAOCONTRATO  WITH (NOLOCK) ON VERSAOCONTRATO.CONTRATO = CONTRATO.CONTRATO
WHERE 
	CONTRATO.SITUACAOCONTRATO = 6 
	AND VERSAOCONTRATO.SITUACAOCONTR = 3

--COMMIT TRANSACTION C1;
--ROLLBACK TRANSACTION C1;
